### ISSUE TITLE
Can't find it in-game

### ISSUE THREAD

**Issue by Wozza123** [cpiehl/camber-extravaganza#2]
Hi, I've installed camber extravaganza into AC with no issues and I have checked the box in the options screen so I know it is there, however when I am at the track I can't find the the option for it on the right hand menu.

Do you know what the problem might be?

Thanks.

**Comment by cpiehl** [comment]
In general this has been caused by the filename being incorrect.  Make sure the files are named exactly like this:

`assettocorsa\apps\python\camber-extravaganza\camber-extravaganza.py`
`assettocorsa\apps\python\camber-extravaganza\tyres-data.json`

**Comment by Wozza123** [comment]
Thanks for replying. :)

You were correct. For some reason mine was called: assettocorsa\apps\python\camber-extravaganza-**master**

However that was the way it installed it so is there an error with the installer?

Great app!

**Comment by cpiehl** [comment]
Added the proper folder name in the download so it should be easier to install without errors now.
